config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get  'home', to: 'main#index'

  get 'users/:username', to: 'givers#show', as: :giver

  get 'charities/apply', to: 'charities#verification'

  devise_for :managers, :controllers => { sessions: "managers_sessions" }
  devise_for :givers, :controllers => { :omniauth_callbacks => "givers_omniauth_callbacks" }

  namespace :manager do
    root 'charities#show'

    get 'mail', to: 'mail#show'
    post 'mail/followers', to: 'mail#followers'

    resources :charities,         only: [:show] do
      resources :givers,          only: [:index, :show]
      resources :events do
        resources :givers,        only: [:index, :show]
        resources :registrations, only: [:index, :show, :update, :destroy]
      end
      resources :needs do
        resources :givers,        only: [:index, :show]
        resources :donations,     only: [:index, :show, :update, :destroy]
      end
    end
  end

  resources :charities,         only: [:index, :show] do
    resources :subscriptions,   only: [:create, :destroy]
    resources :events,          only: :show do
      resources :registrations, except: :index
    end
    resources :needs,           only: :show do
      resources :donations,     except: :index
    end
  end

  namespace :api, defaults: { format: :json } do
    get 'charities',      to: 'api#charities'
    post 'search',        to: 'api#search'
    post 'auth/verify',   to: 'auth#verify'
    post 'auth/giver',    to: 'auth#giver'
    post 'auth/charity',  to: 'auth#charity'
    post 'auth/follow',   to: 'auth#follow'
    post 'auth/donate',   to: 'auth#donate'
    post 'auth/register', to: 'auth#register'

    get 'auth/test', to: 'auth#test'
  end

  mount ActionCable.server => '/cable'
end

app/models/giver.rb
class Giver < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :subscriptions
  has_many :locations
  has_many :donations
  has_many :registrations
  has_many :needs,              through: :donations
  has_many :events,             through: :registrations
  has_many :followed_charities, through: :subscriptions, source: :charity

  validates_uniqueness_of :username

  def self.from_omniauth(auth)
    where(fbid: auth.uid).first_or_create do |giver|
      giver.fbid = auth.uid
      giver.email = auth.info.email
      giver.first_name = /([^\s]+)/.match(auth.info.name)[0]
      giver.last_name = /(?:\S+ ){1}(\S+)/.match(auth.info.name)[1]
      giver.password = Devise.friendly_token[0,20]
      giver.username = giver.first_name.downcase + giver.last_name.downcase
      giver.image_url = auth.info.image
    end
  end

  def self.from_mobile_omniauth(auth)
    where(fbid: auth['id']).first_or_create do |giver|
      giver.fbid = auth['id']
      giver.email = auth['email']
      giver.first_name = auth['first_name']
      giver.last_name = auth['last_name']
      giver.password = Devise.friendly_token[0,20]
      giver.username = giver.first_name.downcase + giver.last_name.downcase
      giver.image_url = auth['picture']['data']['url']
    end
  end
end

app/controllers/givers_controller.rb
class GiversController < ApplicationController
  before_action :authorize_giver

  def show
    @giver = Giver.find_by(username: params[:username])
    @charities = @giver.followed_charities
    @events = @giver.events
    @needs = @giver.needs
  end

  private

  def authorize_giver
    if current_giver != Giver.find_by!(username: params[:username])
      redirect_to root_path
    end
  end
end

app/controllers/manager/givers_controller.rb
class Manager::GiversController < Manager::ApplicationController
  before_action :find_charity, :find_manager

  def index
    # could just call @charity.followers in view, etc. ?
    @followers = @charity.followers
    @donors = @charity.donors
    @volunteers = @charity.volunteers
  end

  def show
    @giver = Giver.find(params[:id])
  end

  private

  def find_charity
    @charity = Charity.find(params[:charity_id])
  end

  def find_manager
    @manager = @charity.manager
  end

end

app/views/givers/show.html.erb
<div class="jumbotron charity-user-hero">
	<div class="container">
		<h1 class="text-center"><%= @giver.username %></h1>
		<p class="text-center">Karma Points: <%= @giver.points %></p>
	</div>
</div>

<div class="container">
	<div class="row">

		<div class="col-md-4">
  		<div class="panel panel-info">
  			<div class="panel-heading">
					<h2 class="text-center">Registered Events</h2>
				</div>

				<div class="panel-body">
					<div class="list-group text-center">

						<% @events.each do |event| %>
						<a class="list-group-item list-group-item-action" data-toggle="collapse" href="#collapseEvent<%= event.id.to_s%>" aria-expanded="false" aria-controls="#collapseEvent<%= event.id.to_s%>">
				    	<h5 class="list-group-item-heading"><%= event.name %></h5>
	   		    	<p class="list-group-item-text"><%= event.description %></p>
						</a>
						<!-- Maybe add a table here-->
						<div class="collapse" id="collapseEvent<%= event.id.to_s%>">
						  <div class="card card-block">
						    <%= link_to "View the event", charity_event_path(event.charity, event), class: 'btn btn-primary' %>
							  <p>Approved Hours: 38</p>
							  <p>Pending Hours: 8</p>
							  </div>
							</div>
						<% end %>

					</div>
				</div>
			</div>
		</div>

		<div class="col-md-4">
			<div class="panel panel-info">
  			<div class="panel-heading">
					<h2 class="text-center">Donated Needs</h2>
				</div>

				<div class="panel-body">
					<div class="list-group text-center">
						<% @needs.each do |need| %>
							<a class="list-group-item list-group-item-action" data-toggle="collapse" href="#collapseNeed<%= need.id.to_s%>" aria-expanded="false" aria-controls="#collapseNeed<%= need.id.to_s%>">
					    	<h5 class="list-group-item-heading"><%= need.name %></h5>
			 		    	<p class="list-group-item-text"><%= need.description %></p>
							</a>
							<!-- Maybe add a table here-->
						<div class="collapse" id="collapseNeed<%= need.id.to_s %>">
						  <div class="card card-block">
							<%= link_to "View this need", charity_need_path(need.charity, need), class: 'btn btn-primary' %>
						  <p>Pending Quantity: 10</p>
							<p>Approved Quantity: 10</p>
						  </div>
						</div>
					<% end %>
					</div>
				</div>
			</div>
		</div>

		<div class="col-md-4">
			<div class="panel panel-info">
  			<div class="panel-heading">
					<h2 class="text-center">Followed Charities</h2>
				</div>

			<div class="panel-body">
				<div class="list-group text-center">
					<% @charities.each do |charity| %>
				    <a href="<%= charity_path(charity)%>" class="list-group-item list-group-item-action">
				    	<h5 class="list-group-item-heading"><%= charity.name %></h5>
				    	<p class="list-group-item-text"><%= charity.description %></p>
				    </a>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>