config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get  'home', to: 'main#index'

  get 'users/:username', to: 'givers#show', as: :giver

  get 'charities/apply', to: 'charities#verification'

  devise_for :managers, :controllers => { sessions: "managers_sessions" }
  devise_for :givers, :controllers => { :omniauth_callbacks => "givers_omniauth_callbacks" }

  namespace :manager do
    root 'charities#show'

    get 'mail', to: 'mail#show'
    post 'mail/followers', to: 'mail#followers'

    resources :charities,         only: [:show] do
      resources :givers,          only: [:index, :show]
      resources :events do
        resources :givers,        only: [:index, :show]
        resources :registrations, only: [:index, :show, :update, :destroy]
      end
      resources :needs do
        resources :givers,        only: [:index, :show]
        resources :donations,     only: [:index, :show, :update, :destroy]
      end
    end
  end

  resources :charities,         only: [:index, :show] do
    resources :subscriptions,   only: [:create, :destroy]
    resources :events,          only: :show do
      resources :registrations, except: :index
    end
    resources :needs,           only: :show do
      resources :donations,     except: :index
    end
  end

  namespace :api, defaults: { format: :json } do
    get 'charities',      to: 'api#charities'
    post 'search',        to: 'api#search'
    post 'auth/verify',   to: 'auth#verify'
    post 'auth/giver',    to: 'auth#giver'
    post 'auth/charity',  to: 'auth#charity'
    post 'auth/follow',   to: 'auth#follow'
    post 'auth/donate',   to: 'auth#donate'
    post 'auth/register', to: 'auth#register'

    get 'auth/test', to: 'auth#test'
  end

  mount ActionCable.server => '/cable'
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :charity
  has_many   :notifications
end

app/controllers/manager/application_controller.rb
class Manager::ApplicationController < ApplicationController
  before_action :authorize_manager

  private

  def authorize_manager
    if Charity.find_by!(id: params[:charity_id]).manager
      manager_id = Charity.find_by!(id: params[:charity_id]).manager.id
      if current_manager != Manager.find_by!(id: manager_id)
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/manager/charities_controller.rb
class Manager::CharitiesController < ApplicationController
	before_action :authorize_manager_show

	def show
		@manager = current_manager
		@charity = Charity.find(params[:id])

    @followers = @charity.followers
    @volunteers = @charity.volunteers
    @donors = @charity.donors

    @registrations = @charity.registrations.pending
    @donations = @charity.donations.pending
		@notifications = @manager.notifications.for_display

    @events = @charity.events
    @needs = @charity.needs

    @event = Event.new
    @need = Need.new
	end

	private

  def authorize_manager_show
		if Charity.find_by!(id: params[:id]).manager
    	manager_id = Charity.find_by!(id: params[:id]).manager.id
	    if current_manager != Manager.find_by!(id: manager_id)
	      redirect_to root_path
	    end
		else
			redirect_to root_path
		end
  end
end

app/controllers/manager/donations_controller.rb
class Manager::DonationsController < Manager::ApplicationController
  before_action :find_charity
  before_action :find_donation

  def show
  end

  def update
    @donation.approve_quantity
    @donation.save!

    # update user points on user object

    # redirect for testing purposes:
    redirect_to manager_charity_url(@charity)
  end

  def destroy
    @donation.destroy

    # redirect for testing purposes:
    redirect_to manager_charity_url(@charity)
  end

  private

  def find_charity
    @charity = Charity.find(params[:charity_id])
  end

  def find_donation
    @donation = Donation.find(params[:id])
  end
end

app/controllers/manager/events_controller.rb
class Manager::EventsController < Manager::ApplicationController
	before_action :find_charity
	before_action :find_event, only: [:show, :edit, :update, :destroy]

	def index
		@events = @charity.events
	end

	def show
		@givers = @event.givers
	end

	def new
		@event = Event.new
	end

	def create
		@event = @charity.events.new(event_params)

		if @event.save
			redirect_to manager_charity_path(@charity)
		else
			@errors = @event.errors.full_messages
			render "manager/events#show"
		end
	end

	def edit
	end

	def update
		if @event.update(event_params)
			redirect_to manager_charity_url(@charity)
		else
			@errors = @event.errors.full_messages
			render "manager/events#edit"
		end
	end

	def destroy
		@event.destroy

		redirect_to manager_charity_url(@charity)
	end

	private

	def event_params
		params.require(:event).permit(:name, :description, :start, :end, :givers_needed)
	end

	def find_charity
		@charity ||= Charity.find(params[:charity_id])
	end

	def find_event
		@event ||= Event.find(params[:id])
	end
end

app/controllers/manager/givers_controller.rb
class Manager::GiversController < Manager::ApplicationController
  before_action :find_charity, :find_manager

  def index
    # could just call @charity.followers in view, etc. ?
    @followers = @charity.followers
    @donors = @charity.donors
    @volunteers = @charity.volunteers
  end

  def show
    @giver = Giver.find(params[:id])
  end

  private

  def find_charity
    @charity = Charity.find(params[:charity_id])
  end

  def find_manager
    @manager = @charity.manager
  end

end

app/controllers/manager/mail_controller.rb
class Manager::MailController < ApplicationController
  def show
    render partial: 'manager/modals/mailer'
  end

  def followers
    ManagerMailer.follower_email(current_manager, params[:subject], params[:body]).deliver_later
  end
end

app/controllers/manager/needs_controller.rb
class Manager::NeedsController < Manager::ApplicationController
  before_action :charity
  before_action :need, only: [:show, :edit, :update, :destroy]

  def index
    @needs = @charity.needs
  end

  def show
    @givers = @need.givers
  end

  def new
    @need = Need.new
  end

  def create
    @need = @charity.needs.new(need_params)

    if @need.save
      redirect_to manager_charity_path(@charity)
    else
      @errors = @need.errors.full_messages
      render "manager/needs#show"
    end
  end

  def edit
  end

  def update
    if @need.update(need_params)
      redirect_to manager_charity_url(@charity)
    else
      @errors = @need.errors.full_messages
      render "manager/needs#edit"
    end
  end

  def destroy
    @need.destroy

    redirect_to manager_charity_url(@charity)
  end

  private

  def need_params
    params.require(:need).permit(:name, :description, :quantity_needed, :status)
  end

  def charity
    @charity ||= Charity.find(params[:charity_id])
  end

  def need
    @need ||= Need.find(params[:id])
  end
end

app/controllers/manager/registrations_controller.rb
class Manager::RegistrationsController < Manager::ApplicationController
  before_action :find_charity
  before_action :find_registration

  def show
  end

  def update
    @registration.approve_hours
    @registration.save!
    # update user points

    # redirect for testing purposes:
    redirect_to manager_charity_url(@charity)
  end

  def destroy
    @registration.destroy

    # redirect for testing purposes:
    redirect_to manager_charity_url(@charity)
  end

  private

  def find_charity
    @charity = Charity.find(params[:charity_id])
  end

  def find_registration
    @registration = Registration.find(params[:id])
  end
end

app/helpers/manager/charities_helper.rb
module Manager::CharitiesHelper
end

app/helpers/manager/donations_helper.rb
module Manager::DonationsHelper
end

app/helpers/manager/events_helper.rb
module Manager::EventsHelper
end

app/views/manager/modals/_all_givers.html.erb
<div class="modal fade" id="allGiversModal" tabindex="-1" role="dialog" aria-labelledby="allGiversModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="allGiversModalLabel">Your Givers</h4>
      </div>

      <div class="modal-body">
        <div>
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#followers" aria-controls="followers" role="tab" data-toggle="tab">Followers</a></li>
            <li role="presentation"><a href="#donors" aria-controls="donors" role="tab" data-toggle="tab">Donors</a></li>
            <li role="presentation"><a href="#volunteers" aria-controls="volunteers" role="tab" data-toggle="tab">Volunteers</a></li>
          </ul>

          <!-- Tab panes -->
          <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="followers">
              <%= render partial: 'manager/partials/followers'%>
            </div>
            <div role="tabpanel" class="tab-pane" id="donors">
              <%= render partial: 'manager/partials/donors'%>
            </div>
            <div role="tabpanel" class="tab-pane" id="volunteers">
              <%= render partial: 'manager/partials/volunteers'%>
            </div>
          </div>
        </div>
      </div>
      </div>

      <div class="modal-footer">
      </div>

    </div>
  </div>
</div>

app/views/manager/modals/_approve_donation.html.erb
<div class="modal fade" id=<%= "donationApprovalModal#{donation.id}" %> tabindex="-1" role="dialog" aria-labelledby="donationApprovalModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id=<%= "donationApprovalModalLabel#{donation.id}" %>>Please approve this <em><%= donation.need.name %></em> donation.</h4>
      </div>

      <div class="modal-body">
        <h3>Giver <em><%= donation.giver.username %></em> donated <%= donation.quantity_pending %> <%= donation.need.name %>.</h3>
      </div>

      <div class="modal-footer">
        <%= form_for [:manager, @charity, donation.need, donation], method: 'put', class: 'form-inline' do |f| %>
          <%= f.submit :Approve, class: "btn approve-btn btn-block" %>
        <% end %>

        <%= form_for [:manager, @charity, donation.need, donation], method: 'delete', class: 'form-inline' do |f| %>
          <%= f.submit :Deny, class: "btn deny-btn btn-block" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/manager/modals/_approve_registration.html.erb
<div class="modal fade" id=<%= "regisApprovalModal#{registration.id}" %> tabindex="-1" role="dialog" aria-labelledby="regisApprovalModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id=<%= "regisApprovalModalLabel#{registration.id}" %>>Please approve these volunteer hours.</h4>
      </div>

      <div class="modal-body">
        <h3>Giver <em><%= registration.giver.username %></em> volunteered for <%= registration.pending_hours %> hours<br>during the <%= registration.event.name %>.</h3>
      </div>

      <div class="modal-footer">
        <%= form_for [:manager, @charity, registration.event, registration], method: 'put' do |f| %>
          <%= f.submit :Approve, class: "btn approve-btn btn-block" %>
        <% end %>

        <%= form_for [:manager, @charity, registration.event, registration], method: 'delete' do |f| %>
          <%= f.submit :Deny, class: "btn deny-btn btn-block" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/manager/modals/_drawer.html.erb
<div id="drawerExample" class="drawer dw-xs-10 dw-sm-6 dw-md-4 fold" aria-labelledby="drawerExample" >
	<div class="drawer-controls">
		<a href="#drawerExample" data-toggle="drawer" aria-foldedopen="false" aria-controls="drawerExample" class="btn man-dash-top-btn btn-sm">Menu</a>
	</div>
	<div class="drawer-contents">
		<div class="drawer-heading" >
			<h2 class="drawer-title"><%= image_tag(@charity.image_url, size: "50x50", class: 'img-circle')%> <%= @charity.name %>'s Dashboard</h2>
		</div>
		<div class="drawer-body">
			<p>Managed by <em><%=@charity.manager.username%></em></p>
		</div>
		<ul class="drawer-nav">
			<p><button type="button" class="btn man-dash-top-btn btn-block" data-toggle="modal" data-target="#newEventModal">Create An Event</button></p>
			<p><button type="button" class="btn man-dash-top-btn btn-block" data-toggle="modal" data-target="#newNeedModal">Add A Need</button></p>
			<p><button type="button" class="btn man-dash-top-btn btn-block" data-toggle="modal" data-target="#allGiversModal">View Givers</button></p>
			<p><button type="button" class="btn man-dash-top-btn btn-block" data-toggle="modal" data-target="#newEmailModal">Send Email</button></p>
		</ul>
		<div class="drawer-footer">
		</div>
	</div>
</div>
<%= render partial: 'manager/modals/new_event' %>
<%= render partial: 'manager/modals/new_need' %>
<%= render partial: 'manager/modals/all_givers'%>
<%= render partial: 'manager/modals/mailer'%>

app/views/manager/modals/_edit_event.html.erb
<div class="modal fade" id=<%= "editEventModal#{event.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "editEventModalLabel#{event.id}" %> aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id=<%= "editEventModal#{event.id}" %>>Edit <%= event.name %> Event</h4>
      </div>

      <div class="modal-body">
        <%= form_for [:manager, @charity, event], method: 'put' do |f|%>
          <div>
            <%= f.label :name %>:
            <%= f.text_field :name, value: event.name %>
          </div>

          <div>
            <%= f.label :starts %>:
            <%= f.datetime_field :start %>
          </div>

          <div>
            <%= f.label :ends %>:
            <%= f.datetime_field :end %>
          </div>

          <div>
            <%= f.label :description %>:
            <%= f.text_area :description, value: event.description %>
          </div>

          <div>
            <%= f.label :givers_needed %>:
            <%= f.text_field :givers_needed, value: event.givers_needed %>
          </div>
      </div>

      <div class="modal-footer">
          <%= f.submit :update, class: "btn man-dash-top-btn btn-block" %>
      </div>
        <%end%>

    </div>
  </div>
</div>

app/views/manager/modals/_edit_need.html.erb
<div class="modal fade" id=<%= "editNeedModal#{need.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "editNeedModalLabel#{need.id}" %> aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id=<%= "editNeedModal#{need.id}" %>>Edit <%= need.name %> need</h4>
      </div>

      <div class="modal-body">
        <% if @errors %>
          <ul>
            <% @errors.each do |error| %>
            <li><%= error %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_for [:manager, @charity, need] do |f|%>
          <div>
            <%= f.label :item_name %>:
            <%= f.text_field :name, value: need.name %>
          </div>

          <div>
            <%= f.label :description %>:
            <%= f.text_area :description, value: need.description %>
          </div>

          <div>
            <%= f.label :quantity_needed %>:
            <%= f.text_field :quantity_needed, value: need.quantity_needed %>
          </div>

          <div>
            <%= f.label :status %>
            <%= f.select :status, options_for_select([["active", "active"], ["inactive", "inactive"]])%>
          </div>
      </div>

      <div class="modal-footer">
          <%= f.submit :update, class: "btn man-dash-top-btn btn-block" %>
      </div>
        <%end%>

    </div>
  </div>
</div>

app/views/manager/modals/_mailer.html.erb
<div class="modal fade email-modal" id="newEmailModal" tabindex="-1" role="dialog" aria-labelledby="newEmailModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="newEmailModalLabel">
          Email Followers
        </h4>
      </div>

      <div class="modal-body">
        <%= form_tag manager_mail_followers_path, id: 'email-form', method: :post do %>
        <div class="form-group">
          <%= label_tag :subject, "Subject:", class: "col-form-label"%>
          <%= text_field_tag :subject, nil, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= label_tag :body, "Body:", class: "col-form-label"%>
          <%= text_area_tag :body, nil, class: 'form-control'%>
        </div>
      </div>

      <div class="modal-footer">
        <button type="submit" form="email-form" class="btn man-dash-top-btn btn-block" data-toggle="modal" data-target=".email-modal">Send</button>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%= render partial: 'manager/modals/mailer_success' %>

app/views/manager/modals/_mailer_success.html.erb
<div class="modal fade email-modal" id="emailSuccessModal" tabindex="-1" role="dialog" aria-labelledby="emailSuccessModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="emailSuccessModalLabel">
          Email sent!
        </h4>
      </div>
    </div>
  </div>
</div>

app/views/manager/modals/_new_event.html.erb
<div class="modal fade" id="newEventModal" tabindex="-1" role="dialog" aria-labelledby="newEventModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="newEventModalLabel">Create An Event</h4>
      </div>

      <div class="modal-body">
        <% if @errors %>
          <ul>
            <% @errors.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        <% end %>

        <!-- begin form -->
        <%= form_for [:manager, @charity, @event] do |f|%>
          <div class="form-group">
            <%= f.label :name %>:
            <%= f.text_field :name, class: 'form-control'%>
          </div>

          <div class="form-group">
            <%= f.label :starts %>:
            <%= f.datetime_field :start, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :ends %>:
            <%= f.datetime_field :end, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :description %>:
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :givers_needed %>:
            <%= f.text_field :givers_needed, class: 'form-control' %>
          </div>
      </div>

      <div class="modal-footer">
        <%= f.submit class: "btn man-dash-top-btn"%>
      </div>
        <%end%>
        <!-- end form -->

    </div>
  </div>
</div>

app/views/manager/modals/_new_need.html.erb
<div class="modal fade" id="newNeedModal" tabindex="-1" role="dialog" aria-labelledby="newNeedModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="newNeedModalLabel">Add A Need</h4>
      </div>

      <div class="modal-body">
        <% if @errors %>
          <ul>
            <% @errors.each do |error| %>
              <li><%= error %></li>
            <% end %>
          </ul>
        <% end %>

        <!-- begin form -->
        <%= form_for [:manager, @charity, @need] do |f|%>
          <div class="form-group">
            <%= f.label :item_name %>:
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :description %>:
            <%= f.text_area :description, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :quantity_needed %>:
            <%= f.text_field :quantity_needed, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :status %>
            <%= f.select :status, options_for_select([["active", "active"], ["inactive", "inactive"]]), class: 'form-control'%>
          </div>
      </div>

      <div class="modal-footer">
        <%= f.submit class: "btn man-dash-top-btn"%>
      </div>
        <%end%>
        <!-- end form -->

    </div>
  </div>
</div>

app/views/manager/modals/_view_event.html.erb
<div class="modal fade" id=<%= "viewEventModal#{event.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "viewEventModalLabel#{event.id}" %> aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h2 class="modal-title" id=<%= "viewEventModalLabel#{event.id}" %>>Event Page</h2>
      </div>

      <div class="modal-body">
        <p><strong>Starts:</strong> <%= event.start %></p>
        <p><strong>Ends:</strong> <%= event.end %></p>

        <p><strong>Description:</strong> <%= event.description %></p>

        <p><strong>Givers Needed:</strong> <%= event.givers_needed %></p>

        <div class="registered-volunteers">
          <h3>Givers Registered: </h3>

          <% if event.givers.empty? %>
            no volunteers yet
          <% else %>
            <ul>
              <% event.givers[0..10].each do |giver| %>
                <li class="list-unstyled"> <%= giver.username %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

      </div>

      <div class="modal-footer">
        <button type="button" class="btn man-dash-top-btn btn-block" data-toggle="modal" data-target=<%= "#editEventModal#{event.id}" %>>edit</button>
          <%= render partial: 'manager/modals/edit_event', locals: { event: event } %>

        <%= form_for [:manager, @charity, event], method: 'delete' do |f| %>
          <%= f.submit :delete, class: "btn deny-btn btn-block" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/manager/modals/_view_follower.html.erb
<div class="modal fade" id=<%= "viewFollowerModal#{follower.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "viewFollowerModalLabel#{follower.id}" %> aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id=<%= "#viewFollowerModalLabel#{follower.id}" %>>Profile: <%= follower.first_name %> <%= follower.last_name %></h4>
      </div>

      <div class="modal-body">
        <p><%= follower.first_name %> <%= follower.last_name %></p>
        <p><%= follower.username %></p>
        <p><%= follower.email %></p>
      </div>

      <div class="modal-footer">
      </div>

    </div>
  </div>
</div>

app/views/manager/modals/_view_need.html.erb
<div class="modal fade" id=<%= "viewNeedModal#{need.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "viewNeedModalLabel#{need.id}" %> aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h2 class="modal-title" id=<%= "viewNeedModalLabel#{need.id}" %>>Show <%=@need.name%> Need Page</h2>
      </div>

      <div class="modal-body">
        <p><strong>Status:</strong> <%= need.status %></p>

        <p><strong>Description:</strong> <%= need.description %></p>

        <p><strong>Quantity Needed:</strong> <%= need.quantity_needed %></p>

        <div class="donors">
          <h3>Donors: </h3>
          <% if need.givers.empty? %>
            no volunteers yet
            <% else %>
              <ul>
                <% need.givers[0..10].each do |giver| %>
                  <li class="list-unstyled"> <%= giver.username %></li>

                <% end %>
              </ul>
            <% end %>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn man-dash-top-btn btn-block" data-toggle="modal" data-target=<%= "#editNeedModal#{need.id}" %>>edit</button>
          <%= render partial: 'manager/modals/edit_need', locals: { need: need } %>

        <%= form_for [:manager, @charity, need], method: 'delete' do |f| %>
          <%= f.submit :delete, class: "btn deny-btn btn-block" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/manager/modals/_view_volunteer.html.erb
<div class="modal fade" id=<%= "viewVolunteerModal#{volunteer.id}" %> tabindex="-1" role="dialog" aria-labelledby=<%= "viewVolunteerModalLabel#{volunteer.id}" %> aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id=<%= "#viewVolunteerModalLabel#{volunteer.id}" %>>Profile: <%= volunteer.first_name %> <%= volunteer.last_name %></h4>
      </div>

      <div class="modal-body">
        <p><%= volunteer.first_name %> <%= volunteer.last_name %></p>
        <p><%= volunteer.username %></p>
        <p><%= volunteer.email %></p>
      </div>

      <div class="modal-footer">

      </div>

    </div>
  </div>
</div>