config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get  'home', to: 'main#index'

  get 'users/:username', to: 'givers#show', as: :giver

  get 'charities/apply', to: 'charities#verification'

  devise_for :managers, :controllers => { sessions: "managers_sessions" }
  devise_for :givers, :controllers => { :omniauth_callbacks => "givers_omniauth_callbacks" }

  namespace :manager do
    root 'charities#show'

    get 'mail', to: 'mail#show'
    post 'mail/followers', to: 'mail#followers'

    resources :charities,         only: [:show] do
      resources :givers,          only: [:index, :show]
      resources :events do
        resources :givers,        only: [:index, :show]
        resources :registrations, only: [:index, :show, :update, :destroy]
      end
      resources :needs do
        resources :givers,        only: [:index, :show]
        resources :donations,     only: [:index, :show, :update, :destroy]
      end
    end
  end

  resources :charities,         only: [:index, :show] do
    resources :subscriptions,   only: [:create, :destroy]
    resources :events,          only: :show do
      resources :registrations, except: :index
    end
    resources :needs,           only: :show do
      resources :donations,     except: :index
    end
  end

  namespace :api, defaults: { format: :json } do
    get 'charities',      to: 'api#charities'
    post 'search',        to: 'api#search'
    post 'auth/verify',   to: 'auth#verify'
    post 'auth/giver',    to: 'auth#giver'
    post 'auth/charity',  to: 'auth#charity'
    post 'auth/follow',   to: 'auth#follow'
    post 'auth/donate',   to: 'auth#donate'
    post 'auth/register', to: 'auth#register'

    get 'auth/test', to: 'auth#test'
  end

  mount ActionCable.server => '/cable'
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :charity
  has_many   :notifications
end

app/models/need.rb
class Need < ApplicationRecord
  enum status: [ :inactive, :active ]
  
  belongs_to :charity
  has_many   :donations
  has_many   :givers, through: :donations

  validates :name, :description, :charity, :status, presence: true
  validates :quantity_needed, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/manager/application_controller.rb
class Manager::ApplicationController < ApplicationController
  before_action :authorize_manager

  private

  def authorize_manager
    if Charity.find_by!(id: params[:charity_id]).manager
      manager_id = Charity.find_by!(id: params[:charity_id]).manager.id
      if current_manager != Manager.find_by!(id: manager_id)
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/manager/charities_controller.rb
class Manager::CharitiesController < ApplicationController
	before_action :authorize_manager_show

	def show
		@manager = current_manager
		@charity = Charity.find(params[:id])

    @followers = @charity.followers
    @volunteers = @charity.volunteers
    @donors = @charity.donors

    @registrations = @charity.registrations.pending
    @donations = @charity.donations.pending
		@notifications = @manager.notifications.for_display

    @events = @charity.events
    @needs = @charity.needs

    @event = Event.new
    @need = Need.new
	end

	private

  def authorize_manager_show
		if Charity.find_by!(id: params[:id]).manager
    	manager_id = Charity.find_by!(id: params[:id]).manager.id
	    if current_manager != Manager.find_by!(id: manager_id)
	      redirect_to root_path
	    end
		else
			redirect_to root_path
		end
  end
end

app/controllers/manager/donations_controller.rb
class Manager::DonationsController < Manager::ApplicationController
  before_action :find_charity
  before_action :find_donation

  def show
  end

  def update
    @donation.approve_quantity
    @donation.save!

    # update user points on user object

    # redirect for testing purposes:
    redirect_to manager_charity_url(@charity)
  end

  def destroy
    @donation.destroy

    # redirect for testing purposes:
    redirect_to manager_charity_url(@charity)
  end

  private

  def find_charity
    @charity = Charity.find(params[:charity_id])
  end

  def find_donation
    @donation = Donation.find(params[:id])
  end
end

app/controllers/manager/events_controller.rb
class Manager::EventsController < Manager::ApplicationController
	before_action :find_charity
	before_action :find_event, only: [:show, :edit, :update, :destroy]

	def index
		@events = @charity.events
	end

	def show
		@givers = @event.givers
	end

	def new
		@event = Event.new
	end

	def create
		@event = @charity.events.new(event_params)

		if @event.save
			redirect_to manager_charity_path(@charity)
		else
			@errors = @event.errors.full_messages
			render "manager/events#show"
		end
	end

	def edit
	end

	def update
		if @event.update(event_params)
			redirect_to manager_charity_url(@charity)
		else
			@errors = @event.errors.full_messages
			render "manager/events#edit"
		end
	end

	def destroy
		@event.destroy

		redirect_to manager_charity_url(@charity)
	end

	private

	def event_params
		params.require(:event).permit(:name, :description, :start, :end, :givers_needed)
	end

	def find_charity
		@charity ||= Charity.find(params[:charity_id])
	end

	def find_event
		@event ||= Event.find(params[:id])
	end
end

app/controllers/manager/givers_controller.rb
class Manager::GiversController < Manager::ApplicationController
  before_action :find_charity, :find_manager

  def index
    # could just call @charity.followers in view, etc. ?
    @followers = @charity.followers
    @donors = @charity.donors
    @volunteers = @charity.volunteers
  end

  def show
    @giver = Giver.find(params[:id])
  end

  private

  def find_charity
    @charity = Charity.find(params[:charity_id])
  end

  def find_manager
    @manager = @charity.manager
  end

end

app/controllers/manager/mail_controller.rb
class Manager::MailController < ApplicationController
  def show
    render partial: 'manager/modals/mailer'
  end

  def followers
    ManagerMailer.follower_email(current_manager, params[:subject], params[:body]).deliver_later
  end
end

app/controllers/manager/needs_controller.rb
class Manager::NeedsController < Manager::ApplicationController
  before_action :charity
  before_action :need, only: [:show, :edit, :update, :destroy]

  def index
    @needs = @charity.needs
  end

  def show
    @givers = @need.givers
  end

  def new
    @need = Need.new
  end

  def create
    @need = @charity.needs.new(need_params)

    if @need.save
      redirect_to manager_charity_path(@charity)
    else
      @errors = @need.errors.full_messages
      render "manager/needs#show"
    end
  end

  def edit
  end

  def update
    if @need.update(need_params)
      redirect_to manager_charity_url(@charity)
    else
      @errors = @need.errors.full_messages
      render "manager/needs#edit"
    end
  end

  def destroy
    @need.destroy

    redirect_to manager_charity_url(@charity)
  end

  private

  def need_params
    params.require(:need).permit(:name, :description, :quantity_needed, :status)
  end

  def charity
    @charity ||= Charity.find(params[:charity_id])
  end

  def need
    @need ||= Need.find(params[:id])
  end
end

app/controllers/manager/registrations_controller.rb
class Manager::RegistrationsController < Manager::ApplicationController
  before_action :find_charity
  before_action :find_registration

  def show
  end

  def update
    @registration.approve_hours
    @registration.save!
    # update user points

    # redirect for testing purposes:
    redirect_to manager_charity_url(@charity)
  end

  def destroy
    @registration.destroy

    # redirect for testing purposes:
    redirect_to manager_charity_url(@charity)
  end

  private

  def find_charity
    @charity = Charity.find(params[:charity_id])
  end

  def find_registration
    @registration = Registration.find(params[:id])
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  def show
    @charity = Charity.find(params[:charity_id])
    @need = Need.find(params[:id])
    @giver = current_giver
    @donation = @need.donations.find_or_create_by(giver_id: @giver)
    @subscription = @charity.subscriptions.find_by(giver_id: @giver)
  end
end

app/helpers/manager/charities_helper.rb
module Manager::CharitiesHelper
end

app/helpers/manager/donations_helper.rb
module Manager::DonationsHelper
end

app/helpers/manager/events_helper.rb
module Manager::EventsHelper
end

app/views/manager/needs/edit.html.erb
<h1>Manager Dashboard: Edit <%= @need.name %> Need</h1>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [:manager, @charity, @need] do |f|%>
  <div>
    <%= f.label :item_name %>:
    <%= f.text_field :name, value: @need.name %>
  </div>

  <div>
    <%= f.label :description %>:
    <%= f.text_area :description, value: @need.description %>
  </div>

  <div>
    <%= f.label :quantity_needed %>:
    <%= f.text_field :quantity_needed, value: @need.quantity_needed %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.select :status, options_for_select([["Active", "Active"], ["Inactive", "Inactive"]])%>
  </div>

  <%= f.submit %>
<%end%>

app/views/manager/needs/index.html.erb
<h1>Manager Dashboard: Needs for <%= @charity.name %></h1>

<div>
<%= link_to 'Add new need', new_manager_charity_need_path(@charity) %>
</div>

<% @needs.each do |need| %>

  <li>
    <%= need.name %>
      <%= link_to 'show', manager_charity_need_path(@charity, need) %>
      <%= link_to 'update', edit_manager_charity_need_path(@charity, need) %>
      <%= link_to 'destroy', manager_charity_need_path(@charity, need), method: 'delete' %>
  </li>

<% end %>

<div>
  <p> also good to show: # of total givers? needs fulfilled?</p>
</div>

<div>
  <%= link_to '< back to dashboard', manager_charity_path(@charity) %>
</div>

app/views/manager/needs/new.html.erb
<h1>Manager Dashboard: Add New Need</h1>

<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for [:manager, @charity, @need] do |f|%>
  <div>
    <%= f.label :item_name %>:
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>:
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.label :quantity_needed %>:
    <%= f.text_field :quantity_needed %>
  </div>

  <div>
    <%= f.label :status %>
    <%= f.select :status, options_for_select([["active", "active"], ["inactive", "inactive"]])%>
  </div>

  <%= f.submit %>
<%end%>

app/views/manager/needs/show.html.erb
<h1>Manager Dashboard: Show <%=@need.name%> Need Page</h1>

<li>Status: <%= @need.status %></li>

<li>Description: <%= @need.description %></li>

<li>Quantity Needed: <%= @need.quantity_needed %></li>

<div class="donors">
  <h1>Donors: </h1>
  <% if @givers.empty? %>
    no volunteers yet
    <% else %>
      <ul>
        <% @givers.each do |giver| %>
          <li> <%= giver.username %></li>

        <% end %>
      </ul>
    <% end %>
</div>

<div>
  <%= link_to '< back to needs index', manager_charity_needs_path(@charity) %>
</div>